name: work-flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"

      - name: print last
        run: echo "Done Job"
    
    
